### ISSUE TITLE
middleware seems to fail on POST requests

### ISSUE THREAD

**Issue by sebastiaanfranken** [skrajewski/laravel-guard#3]
When I guard a route in my routes.php that's a HTTP POST I run into the nasty bug that the system will run the POST request twice, processing whatever I just posted (usually a form) twice!

My routes (partially):

``` php
Route::group(['prefix' => 'member', 'middleware' => ['auth, 'guard']], function() {

    Route::get('/', ['uses' => 'MemberController@getIndex', 'needs' => 'members.index']);

    Route::get('create', ['uses' => 'MemberController@getCreate', 'needs' => 'members.create']);
    Route::post('create', ['uses' => 'MemberController@postCreate', 'needs' => 'members.create']);

});
```

This all works fine, I'm not running into any problems with the user -> roles or anything like that (user roles work perfect!). It's just that if I go to '/member/create' in my application, fill out the form there and enter "save" the system adds said user twice.

**Comment by skrajewski** [comment]
Hi @sebastiaanfranken,

I found probably mistake in middleware, please check first instruction in _handle_ method

https://github.com/skrajewski/laravel-guard/commit/bb88fb01566b188cbc47703f937ac35e7b0d5c2a#diff-2cad31d3dd2e134f55983b178f8826b4

Without this instruction everything works fine. Please update this package to 0.1.2 version. If you have any other problems please let me know.

Kind regards,
Szymon

**Comment by sebastiaanfranken** [comment]
That did it, this bug is now resolved! Thanks
